blog:
    resource: "@MyBlogBundle/Resources/config/routing.yml"
    prefix: /blog

acme_test:
    resource: "@AcmeTestBundle/Resources/config/routing.yml"
    prefix:   /

acme_hello:
    resource: "@AcmeHelloBundle/Resources/config/routing.yml"
    prefix:   /

